# Generated by Django 4.2.20 on 2025-05-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_honor",
            field=models.BooleanField(default=False),
        ),
    ]
