# Generated by Django 4.2.20 on 2025-05-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_is_honor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_honor",
            new_name="is_owner",
        ),
    ]
