# Generated by Django 4.2.20 on 2025-07-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_is_honor_user_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feedback_given',
            field=models.BooleanField(default=False),
        ),
    ]
