# Generated by Django 4.2.20 on 2025-04-30 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="condition",
        ),
    ]
