# Generated by Django 4.2.20 on 2025-05-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_alter_product_category_alter_product_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publish",
            field=models.BooleanField(default=False),
        ),
    ]
