# Generated by Django 4.2.20 on 2025-05-06 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "content",
            "0012_variant_remove_product_color_remove_product_quantity_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="variant",
        ),
    ]
