# Generated by Django 4.2.20 on 2025-05-06 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_variant_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variant",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_variant",
                to="content.variant",
            ),
        ),
    ]
