# Generated by Django 4.2.20 on 2025-05-06 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_color_order_quantity_order_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
    ]
