# Generated by Django 4.2.20 on 2025-05-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_order_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="user",
            new_name="user_detail",
        ),
    ]
