# Generated by Django 4.2.20 on 2025-05-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_rename_user_order_user_detail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="user_detail",
            new_name="user",
        ),
    ]
