# Generated by Django 4.2.20 on 2025-05-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_rename_user_detail_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Pending", "Pending"), ("Payed", "Payed")],
                default="Pending",
                max_length=100,
                null=True,
            ),
        ),
    ]
