# Generated by Django 4.2.20 on 2025-05-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment",
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Credit Card", "Credit Card"),
                    ("Debit Card", "Debit Card"),
                    ("Cash On Delivery", "Cash On Delivery"),
                ],
                default="Cash On Delivery",
                max_length=100,
            ),
        ),
    ]
