# Generated by Django 4.2.20 on 2025-05-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_remove_product_variant_variant_product"),
        ("order", "0008_remove_order_payment_order_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ManyToManyField(to="content.product"),
        ),
    ]
