# Generated by Django 4.2.20 on 2025-05-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_remove_product_variant_variant_product"),
        ("order", "0010_remove_order_product_orderproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="product",
            field=models.ManyToManyField(
                related_name="order_product", to="content.product"
            ),
        ),
    ]
