# Generated by Django 4.2.20 on 2025-05-07 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_remove_product_variant_variant_product"),
        ("order", "0011_alter_orderproduct_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_product",
                to="order.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="product",
            field=models.ManyToManyField(to="content.product"),
        ),
    ]
