# Generated by Django 4.2.20 on 2025-05-07 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_remove_product_variant_variant_product"),
        ("order", "0012_alter_orderproduct_order_alter_orderproduct_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="product",
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.product",
            ),
        ),
    ]
