# Generated by Django 4.2.20 on 2025-05-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0013_remove_orderproduct_product_orderproduct_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="color",
        ),
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="order",
            name="size",
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
