# Generated by Django 4.2.20 on 2025-05-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0015_alter_order_payment_method_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="total_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
