# Generated by Django 4.2.20 on 2025-05-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0016_payment_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="total_amount",
            field=models.IntegerField(),
        ),
    ]
