# Generated by Django 4.2.20 on 2025-05-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0017_alter_payment_total_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="total_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
