# Generated by Django 4.2.20 on 2025-07-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_payment_status_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='total_price',
        ),
    ]
