# Generated by Django 4.2.20 on 2025-07-05 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_remove_orderproduct_color_remove_orderproduct_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
