# Generated by Django 4.2.20 on 2025-07-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_remove_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount_paid',
            new_name='check_number',
        ),
    ]
