# Generated by Django 4.2.20 on 2025-07-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_rename_amount_paid_payment_check_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='check_number',
            field=models.CharField(max_length=50),
        ),
    ]
