# Generated by Django 4.2.20 on 2025-07-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_payment_check_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='check_number',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
