# Generated by Django 4.2.20 on 2025-07-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_feedback_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='product',
        ),
    ]
