# Generated by Django 4.2.20 on 2025-07-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_remove_feedback_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
    ]
